name: Testing
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      nodejs-version:
        required: true
        type: choice
        options:
          - 22

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v4
      - name: Install NodeJs
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.nodejs-version }}
      - name: Install dependencies
        run: npm ci
      - name: Run lint
        run: npm run lint
      - name: Run tests
        run: npm run test
